name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

jobs:
  test:
    name: test on Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 22
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          # cache: pnpm # TODO Add this line if the projects has lock files (e.g. web apps)

      # TODO Choose one of these
      # - run: pnpm install --frozen-lockfile # If the project DOES have lock files (e.g. web apps)
      # - run: pnpm install # If the project does NOT have lock files (e.g. npm packages)
      - run: pnpm run build
      - run: pnpm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          # cache: pnpm # TODO Add this line if the projects has lock files (e.g. web apps)

      # TODO Choose one of these
      # - run: pnpm install --frozen-lockfile # If the project DOES have lock files (e.g. web apps)
      # - run: pnpm install # If the project does NOT have lock files (e.g. npm packages)
      - run: pnpm run lint

  # ▼▼ TODO Add this section if the project is a web app ▼▼
  deploy:
    needs:
      - test
      - lint
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run deploy
  # ▲▲ TODO Add this section if the project is a web app ▲▲

  # ▼▼ TODO Add this section if the project is an npm package ▼▼
  publish:
    needs:
      - test
      - lint
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true

      - run: pnpm install
      - run: pnpm run build

      - name: Set npm auth token
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
      - run: pnpm run release
  # ▲▲ TODO Add this section if the project is an npm package ▲▲
